dist: trusty
language: go
go:
- "1.11"
- master
cache:
- directories:
  - "$GOPATH/bin"
  - "$GOPATH/pkg"
install: make install
env:
  global:
  - GO111MODULE="on"
script:
- env GO111MODULE=on go run cmd/server/main.go
- make test